words = [
    'travel', 'surgery', 'nightmare', 'elephant', 'physics', 'echo', 'sunset', 
    'whisper', 'telescope', 'scarf', 'football', 'chocolate', 'orange', 'gadget', 
    'tourism', 'Allah', 'therapy', 'vacation', 'comet', 'trip', 'Mecca', 'mountain', 
    'banana', 'technology', 'eclipse', 'twilight', 'adventure', 'essay', 'spice', 
    'airplane', 'couch', 'monitor', 'director', 'beach', 'speaker', 'zakat', 'fusion', 
    'sharia', 'ocean', 'laptop', 'grain', 'article', 'pyramid', 'paradox', 'melon', 
    'asteroid', 'sandstorm', 'lighthouse', 'treatment', 'suit', 'dairy', 'story', 
    'strawberry', 'spectrum', 'dua', 'satellite', 'baseball', 'hamburger', 'rabbit', 
    'jacket', 'mango', 'desert', 'jeans', 'star', 'biology', 'hadith', 'diet', 
    'fruit', 'hail', 'mystery', 'storm', 'horizon', 'tennis', 'ship', 'university', 
    'pencil', 'experiment', 'robot', 'app', 'magazine', 'actor', 'molecule', 'alchemy', 
    'camera', 'invention', 'classroom', 'nurse', 'tool', 'photograph', 'panda', 
    'thunder', 'neutron', 'bookshelf', 'snow', 'clock', 'universe', 'Islam', 'tiger', 
    'psychology', 'poetry', 'prophet', 'oil', 'equation', 'notebook', 'diary', 'flame', 
    'lightning', 'newspaper', 'earth', 'medina', 'journal', 'helicopter', 'nebula', 
    'ai', 'data', 'sculpture', 'quantum', 'internet', 'koala', 'dinosaur', 'chemistry', 
    'library', 'health', 'email', 'kiwi', 'peach', 'giraffe', 'art', 'cookie', 
    'grape', 'painting', 'sunflower', 'galaxy', 'solar', 'lullaby', 'headphones', 
    'journey', 'structure', 'cosmos', 'sugar', 'theory', 'breeze', 'destination', 
    'forest', 'device', 'science', 'medicine', 'symmetry', 'Quran', 'bus', 
    'basketball', 'ramadan', 'truck', 'sofa', 'cherry', 'theater', 'meat', 'paradise', 
    'gloves', 'computer', 'cell', 'dress', 'crystal', 'mirror', 'pasta', 'astronaut', 
    'geography', 'exploration', 'herb', 'nebulae', 'hypothesis', 'blackhole', 
    'thermodynamics', 'astrophysics', 'biosphere', 'cybernetics', 'paleontology', 
    'neurobiology', 'ethics', 'cryptography', 'photonics', 'geology', 'archaeology', 
    'epidemic', 'renaissance', 'algebra', 'calculus', 'topology', 'metaphysics', 
    'tesseract', 'zeitgeist', 'ontology', 'kaleidoscope', 'artificial', 'intelligence', 
    'microorganism', 'evolutionary', 'genetics', 'hermeneutics', 'existentialism'
]

hangman_words_with_hints = {
    'travel': 'The act of going from one place to another.',
    'surgery': 'A medical operation to treat a condition.',
    'nightmare': 'A bad dream that can be scary.',
    'elephant': 'A large animal with a trunk and tusks.',
    'physics': 'The study of matter, energy, and forces.',
    'echo': 'A sound that bounces back from a surface.',
    'sunset': 'The time when the sun goes below the horizon.',
    'whisper': 'Speaking very softly, almost inaudibly.',
    'telescope': 'A tool for looking at stars and planets.',
    'scarf': 'A piece of clothing worn around the neck.',
    'football': 'A sport played with a round ball on a field.',
    'chocolate': 'A sweet treat made from cocoa beans.',
    'orange': 'A citrus fruit that is round and juicy.',
    'gadget': 'A small, innovative electronic or mechanical device.',
    'tourism': 'Traveling for pleasure or exploration.',
    'Allah': 'The Arabic word for God in Islam.',
    'therapy': 'Treatment for mental or physical health.',
    'vacation': 'A time off from work or school for relaxation.',
    'comet': 'A celestial object with a tail that orbits the sun.',
    'trip': 'A short journey or excursion.',
    'Mecca': 'The holiest city in Islam.',
    'mountain': 'A large natural elevation of the earth’s surface.',
    'banana': 'A long, curved yellow fruit.',
    'technology': 'The application of scientific knowledge for practical purposes.',
    'eclipse': 'When one celestial body moves into the shadow of another.',
    'twilight': 'The time between sunset and night.',
    'adventure': 'An exciting or unusual experience.',
    'essay': 'A written composition on a particular topic.',
    'spice': 'A substance used to flavor food.',
    'airplane': 'A vehicle that flies in the sky.',
    'couch': 'A piece of furniture for sitting or lying down.',
    'monitor': 'A screen used to display images or information.',
    'director': 'The person who oversees a film or play.',
    'beach': 'A sandy or pebbly shore by the ocean.',
    'speaker': 'A device that produces sound.',
    'zakat': 'Charitable giving in Islam.',
    'fusion': 'The process of merging two things into one.',
    'sharia': 'Islamic law derived from the Quran and Hadith.',
    'ocean': 'A vast body of saltwater covering the earth.',
    'laptop': 'A portable computer.',
    'grain': 'A small, hard seed used for food.',
    'article': 'A piece of writing in a newspaper or magazine.',
    'pyramid': 'A triangular structure often associated with Egypt.',
    'paradox': 'A seemingly self-contradictory statement or situation.',
    'melon': 'A large, sweet fruit with a thick rind.',
    'asteroid': 'A small rocky body orbiting the sun.',
    'sandstorm': 'A strong wind carrying sand.',
    'lighthouse': 'A tower with a light to guide ships.',
    'treatment': 'Medical care given to someone.',
    'suit': 'A set of formal clothes, often worn with a tie.',
    'dairy': 'Products made from milk.',
    'story': 'A narrative of events, real or imaginary.',
    'strawberry': 'A small red fruit with seeds on the outside.',
    'spectrum': 'A range of colors or other elements.',
    'dua': 'A supplication or prayer in Islam.',
    'satellite': 'An object that orbits a planet.',
    'baseball': 'A sport played with a bat and ball.',
    'hamburger': 'A sandwich made with a beef patty.',
    'rabbit': 'A small mammal with long ears.',
    'jacket': 'A piece of clothing worn over the upper body.',
    'mango': 'A tropical fruit that is sweet and juicy.',
    'desert': 'A dry, sandy area with little rain.',
    'jeans': 'A type of durable pants made from denim.',
    'star': 'A luminous object in the night sky.',
    'biology': 'The study of living organisms.',
    'hadith': 'Sayings and actions of Prophet Muhammad (PBUH).',
    'diet': 'The food that a person habitually eats.',
    'fruit': 'The sweet product of a tree or plant.',
    'hail': 'Frozen raindrops that fall from the sky.',
    'mystery': 'Something that is difficult to explain or understand.',
    'storm': 'A violent disturbance in the atmosphere.',
    'horizon': 'The line where the earth meets the sky.',
    'tennis': 'A sport played with rackets and a ball.',
    'ship': 'A large watercraft used for travel or transport.',
    'university': 'An institution for higher education.',
    'pencil': 'A tool for writing or drawing.',
    'experiment': 'A scientific test or procedure.',
    'robot': 'A machine capable of carrying out tasks.',
    'app': 'A software program for mobile devices.',
    'magazine': 'A periodical publication with articles and images.',
    'actor': 'A person who performs in plays or movies.',
    'molecule': 'The smallest unit of a chemical compound.',
    'alchemy': 'The medieval practice of turning metals into gold.',
    'camera': 'A device used to take photographs.',
    'invention': 'A new device or process created.',
    'classroom': 'A room where teaching occurs.',
    'nurse': 'A healthcare professional who cares for patients.',
    'tool': 'An instrument used to carry out a function.',
    'photograph': 'An image captured by a camera.',
    'panda': 'A black-and-white bear-like mammal.',
    'thunder': 'The sound following a lightning strike.',
    'neutron': 'A subatomic particle with no charge.',
    'bookshelf': 'A piece of furniture to store books.',
    'snow': 'Frozen water crystals falling from the sky.',
    'clock': 'A device used to tell time.',
    'universe': 'All of space and everything in it.',
    'Islam': 'A monotheistic religion founded in the 7th century.',
    'tiger': 'A large carnivorous cat with stripes.',
    'psychology': 'The study of the human mind and behavior.',
    'poetry': 'A form of literature with rhythm and expression.',
    'prophet': 'A person chosen to convey messages from God.',
    'oil': 'A liquid used for cooking or fuel.',
    'equation': 'A mathematical statement of equality.',
    'notebook': 'A book of blank pages for writing.',
    'diary': 'A personal record of daily events.',
    'flame': 'The visible part of a fire.',
    'lightning': 'A flash of light in the sky during storms.',
    'newspaper': 'A printed publication with news and articles.',
    'earth': 'The planet we live on.',
    'medina': 'A historic city in Saudi Arabia.',
    'journal': 'A daily record of personal or professional experiences.',
    'helicopter': 'An aircraft with rotating blades.',
    'nebula': 'A cloud of gas and dust in space.',
    'ai': 'Artificial intelligence, machines simulating human tasks.',
    'data': 'Facts or information collected for reference.',
    'sculpture': 'A three-dimensional piece of art.',
    'quantum': 'The smallest amount of a physical entity.',
    'internet': 'A global network for communication and information.',
    'koala': 'A tree-dwelling marsupial from Australia.',
    'dinosaur': 'A prehistoric reptile.',
    'chemistry': 'The study of substances and their interactions.',
    'library': 'A place with a collection of books.',
    'health': 'The state of being free from illness.',
    'email': 'Electronic messages sent over the internet.',
    'kiwi': 'A small fruit with green flesh.',
    'peach': 'A soft, juicy fruit with fuzzy skin.',
    'giraffe': 'The tallest land animal with a long neck.',
    'art': 'Creative works such as painting or sculpture.',
    'cookie': 'A sweet baked treat.',
    'grape': 'A small, round fruit often used for wine.',
    'painting': 'An artwork made with paint.',
    'sunflower': 'A tall plant with a large yellow flower.',
    'galaxy': 'A massive system of stars, gas, and dust.',
    'solar': 'Relating to the sun.',
    'lullaby': 'A song sung to help a baby sleep.',
    'headphones': 'A device for listening to audio privately.',
    'journey': 'A trip from one place to another.',
    'structure': 'Something built or organized.',
    'cosmos': 'The universe as a whole.',
    'sugar': 'A sweet substance used in food.',
    'theory': 'A well-substantiated explanation of something.',
    'breeze': 'A gentle wind.',
    'destination': 'The place where someone is going.',
    'forest': 'A large area covered with trees.',
    'device': 'A tool or machine for a specific purpose.',
    'science': 'The study of the natural world.',
    'medicine': 'Substances used to treat illnesses.',
    'symmetry': 'Balanced proportions or arrangement.',
    'Quran': 'The holy book of Islam.',
    'bus': 'A large vehicle for public transport.',
    'basketball': 'A sport played with a hoop and ball.',
    'ramadan': 'The holy month of fasting in Islam.',
    'truck': 'A large vehicle for transporting goods.',
    'sofa': 'A comfortable piece of furniture for sitting.',
    'cherry': 'A small, round red fruit.',
    'theater': 'A place where plays and performances occur.',
    'meat': 'Animal flesh used as food.',
    'paradise': 'A place of great happiness or beauty.',
    'gloves': 'A pair of coverings for hands.',
    'computer': 'A device for processing and storing information.',
    'cell': 'The basic building block of life.',
    'dress': 'A piece of clothing for women or girls.',
    'crystal': 'A clear, transparent mineral.',
    'mirror': 'A surface that reflects images.',
    'pasta': 'A type of Italian food made from flour.',
    'astronaut': 'A person who travels into space.',
    'geography': 'The study of the earth’s features.',
    'exploration': 'The act of traveling to discover new places.',
    'herb': 'A plant used for flavor or medicine.',
    'nebulae': 'Plural of nebula, clouds in space.',
    'hypothesis': 'A proposed explanation for something.',
    'blackhole': 'A region in space with strong gravity.',
    'thermodynamics': 'The study of heat and energy transfer.',
    'astrophysics': 'The study of the physics of celestial bodies.',
    'biosphere': 'The regions of Earth where life exists.',
    'cybernetics': 'The study of systems and control in machines.',
    'paleontology': 'The study of fossils.',
    'neurobiology': 'The study of the nervous system.',
    'ethics': 'Moral principles governing behavior.',
    'cryptography': 'The practice of secure communication.',
    'photonics': 'The study of light and its applications.',
    'geology': 'The study of the Earth’s physical structure.',
    'archaeology': 'The study of ancient artifacts and sites.',
    'epidemic': 'A widespread outbreak of a disease.',
    'renaissance': 'A cultural rebirth or revival.',
    'algebra': 'A branch of mathematics involving variables.',
    'calculus': 'A branch of mathematics dealing with rates of change.',
    'topology': 'The study of spatial properties preserved under transformation.',
    'metaphysics': 'The study of existence and reality.',
    'tesseract': 'A four-dimensional cube.',
    'zeitgeist': 'The spirit or mood of a particular time.',
    'ontology': 'The study of being and existence.',
    'kaleidoscope': 'An instrument showing changing patterns.',
    'artificial': 'Made by humans, not natural.',
    'intelligence': 'The ability to learn and understand.',
    'microorganism': 'A tiny organism like bacteria.',
    'evolutionary': 'Related to the process of evolution.',
    'genetics': 'The study of genes and heredity.',
    'hermeneutics': 'The study of interpretation, especially of texts.',
    'existentialism': 'A philosophy emphasizing individual existence.'
}


# print(len(set(hangman_words)))
# print(len(set(hangman_words_with_hints.keys())))